import type { Metadata } from "next";
import { Open_Sans, Nunito } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import "../styles/globals.css";
import Main from "./main";
import { ReactNode } from "react";
import { theme } from "@/app/theme/theme";
import "animate.css";
import { createClient } from "@/utils/supabase/server";
import { User } from "@supabase/supabase-js";
import { trpc } from "@/utils/trpc";

const openSans = Nunito({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const supabase = createClient();

  const { data, error } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased`}>
        <ChakraProvider theme={theme}>
          <Main user={data.user as User}>{children}</Main>
        </ChakraProvider>
      </body>
    </html>
  );
}
